version: '3.1'

services:
  drupal:
    image: drupal:latest # Latest version of drupal
    ports:
      - 8080:80 # Expose 8080 on host and sent to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres:latest # Latest version of postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_secret
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - db_secret

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:

secrets:
  db_secret:
    external: true
