version: '2'

services:
  back:
    build: .
    image: custom-drupal # Latest version of drupal
    ports:
      - 8080:80 # Expose 8080 on host and sent to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always

  db:
    image: postgres:latest # Latest version of postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data: